import os
import json
from google import genai
from google.genai import types
from sqlmodel import Session
from app.services import eda_service
from app.models.dataset import Dataset

def get_client():
    """Initializes the Gemini client using the key from the .env file."""
    return genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

def process_message(dataset_id: int, message: str, session: Session):
    """
    Advanced Intelligence Node: Processes natural language queries about 
    the dataset using Gemini 2.0 Flash Lite.
    """
    # 1. Retrieve the dataset record and forensic audit results
    dataset = session.get(Dataset, dataset_id)
    if not dataset:
        return {"response": "Relational link failed: Dataset node not found."}

    # Fetch context from the Discovery Engine (EDA Service)
    summary = eda_service.get_summary_statistics(dataset_id, session)
    correlations = eda_service.get_correlation_matrix(dataset_id, session)
    
    client = get_client()
    
    # 2. Build the Intelligence Node prompt with explicit data grounding
    system_instruction = f"""
    You are A.V.I.S (Analytical Visual Intelligence System), a forensic data expert.
    The user is currently analyzing the dataset: '{dataset.filename}'.
    
    FORENSIC DATA CONTEXT:
    - Total Rows: {summary.get('total_rows')}
    - Columns and Numerical Stats: {json.dumps(summary.get('numeric'))}
    - Discovered Relationships: {json.dumps(correlations.get('top_discoveries'))}
    
    INSTRUCTIONS:
    - Explain patterns like a professional data scientist, but keep it accessible for students.
    - Be precise about averages, standard deviations, and correlations found in the context.
    - If the user asks for a 'plot', 'chart', or 'graph', suggest the best columns for X and Y axes.
    - IMPORTANT: If you suggest a visualization, end your message with this exact JSON block:
      [PLOT_CONFIG: {{"chartType": "bar|scatter|line|pie", "xColumn": "col1", "yColumn": "col2"}}]
    """

    try:
        # 3. Generate response using the high-quota Lite model
        response = client.models.generate_content(
            model="gemini-2.0-flash-lite",
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.7
            ),
            contents=message
        )
        
        text = response.text
        plot_config = None

        # 4. Extract Plotting Instructions if generated by the AI
        if "[PLOT_CONFIG:" in text:
            try:
                # Parse the JSON config from the AI response
                config_str = text.split("[PLOT_CONFIG:")[1].split("]")[0]
                plot_config = json.loads(config_str)
                # Clean the visible text response
                text = text.split("[PLOT_CONFIG:")[0].strip()
            except Exception:
                pass

        return {
            "response": text,
            "plot_config": plot_config
        }
        
    except Exception as e:
        # Standardized Error Mapping for UI feedback
        return {"response": f"Intelligence Node Anomaly: {str(e)}"}